const data = [
  {
    id: "2019121834524",
    title: "I like to beat the brush",
    body: "We're trying to teach you a technique here and how to use it. You can do anything here. So don't worry about it. You can bend rivers. But when I get home, the only thing I have power over is the garbage. These trees are so much fun. I get started on them and I have a hard time stopping. Take your time. Speed will come later. Exercising the imagination, experimenting with talents, being creative; these things, to me, are truly the windows to your soul. Even trees need a friend. We all need friends. Now we can begin working on lots of happy little things. Van Dyke Brown is a very nice brown, it's almost like a chocolate brown. If you've been in Alaska less than a year you're a Cheechako.",
    editing: false,
    saved: true,
    votes: 20,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "food",
  },
  {
    id: "2019121834525",
    title:
      "From all of us here, I want to wish you happy painting and God bless, my friends",
    body: "It's cold, but it's beautiful. Zip. That easy. Just beat the devil out of it. Look around, look at what we have https://www.youtube.com/ . Beauty is everywhere, you only have to look to see it.",
    editing: false,
    saved: true,
    votes: 2,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "gadgets",
  },
  {
    id: "2019121834523",
    title: "See",
    body: "Anything that you believe you can do strong enough, you can do. Anything. As long as you believe. You can create the world you want to see and be a part of. You have that power. Volunteering your time; it pays you and your whole community fantastic dividends. A big strong tree needs big strong roots.",
    editing: false,
    saved: false,
    votes: 3,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "photography",
  },
  {
    id: "2019121834522",
    title: "The secret to doing anything is believing that you can do it",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    editing: false,
    saved: false,
    votes: 4,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "gaming",
  },
  {
    id: "2019121834521",
    title: "You have freedom here",
    body: "The only guide is your heart. You don't have to be crazy to do this but it does help. Just let go - and fall like a little waterfall.",
    editing: false,
    saved: false,
    votes: 5,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "travel",
  },
  {
    id: "2019121834520",
    title: "Painting should do one thing",
    body: "It should put happiness in your heart. I will take some magic white, and a little bit of Vandyke brown and a little touch of yellow. We start with a vision in our heart, and we put it on canvas. It's hard to see things when you're too close. Take a step back and look. That is when you can experience true joy, when you have no fear. We must be quiet, soft and gentle.",
    editing: false,
    saved: false,
    votes: 6,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "art",
  },
  {
    id: "2019121834519",
    title: "La- da- da- da- dah",
    body: "I thought today we would make a happy little stream that's just running through the woods here.",
    editing: false,
    saved: false,
    votes: 7,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "food",
  },
  {
    id: "2019121834518",
    title: "Just be happy",
    body: "Everyone wants to enjoy the good parts - but you have to build the framework first. Every highlight needs it's own personal shadow. And maybe, maybe, maybe... Everybody needs a friend.",
    editing: false,
    saved: false,
    votes: 8,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "gaming",
  },
  {
    id: "2019121834517",
    title: "See how easy it is to create a little tree right in your world",
    body: "Didn't you know you had that much power? You can move mountains. You can do anything. There is immense joy in just watching - watching all the little creatures in nature.",
    editing: false,
    saved: false,
    votes: 9,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "travel",
  },
  {
    id: "2019121834516",
    title: "Only think about one thing at a time",
    body: "Don't forget to tell these special people in your life just how special they are to you. You can't have light without dark. You can't know happiness unless you've known sorrow. We'll make some happy little bushes here.",
    editing: false,
    saved: false,
    votes: 10,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "movies",
  },
  {
    id: "2019121834515",
    title:
      "From all of us here, I want to wish you happy painting and God bless, my friends",
    body: "It's cold, but it's beautiful. Zip. That easy. Just beat the devil out of it. Look around, look at what we have https://www.youtube.com/ . Beauty is everywhere, you only have to look to see it.",
    editing: false,
    saved: true,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "movies",
  },
  {
    id: "2019121834514",
    title: "I like to beat the brush",
    body: "Use your imagination, let it go. Use what you see, don't plan it. There comes a nice little fluffer. We don't need any guidelines or formats. All we need to do is just let it flow right out of us. If we're gonna walk though the woods, we need a little path.",
    editing: false,
    saved: true,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "politics",
  },
  {
    id: "2019121834513",
    title: "See",
    body: "Anything that you believe you can do strong enough, you can do. Anything. As long as you believe. You can create the world you want to see and be a part of. You have that power. Volunteering your time; it pays you and your whole community fantastic dividends. A big strong tree needs big strong roots.",
    editing: false,
    saved: false,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "travel",
  },
  {
    id: "2019121834512",
    title: "The secret to doing anything is believing that you can do it",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    editing: false,
    saved: false,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "art",
  },
  {
    id: "2019121834511",
    title: "You have freedom here",
    body: "The only guide is your heart. You don't have to be crazy to do this but it does help. Just let go - and fall like a little waterfall.",
    editing: false,
    saved: false,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "food",
  },
  {
    id: "2019121834510",
    title: "Painting should do one thing",
    body: "It should put happiness in your heart. I will take some magic white, and a little bit of Vandyke brown and a little touch of yellow. We start with a vision in our heart, and we put it on canvas. It's hard to see things when you're too close. Take a step back and look. That is when you can experience true joy, when you have no fear. We must be quiet, soft and gentle.",
    editing: false,
    saved: false,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "gaming",
  },
  {
    id: "2019121834509",
    title: "La- da- da- da- dah",
    body: "I thought today we would make a happy little stream that's just running through the woods here.",
    editing: false,
    saved: false,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "hobbies",
  },
  {
    id: "2019121834508",
    title: "Just be happy",
    body: "Everyone wants to enjoy the good parts - but you have to build the framework first. Every highlight needs it's own personal shadow. And maybe, maybe, maybe... Everybody needs a friend.",
    editing: false,
    saved: false,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "hobbies",
  },
  {
    id: "2019121834507",
    title: "See how easy it is to create a little tree right in your world",
    body: "Didn't you know you had that much power? You can move mountains. You can do anything. There is immense joy in just watching - watching all the little creatures in nature.",
    editing: false,
    saved: false,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "art",
  },
  {
    id: "2019121834506",
    title: "Only think about one thing at a time",
    body: "Don't forget to tell these special people in your life just how special they are to you. You can't have light without dark. You can't know happiness unless you've known sorrow. We'll make some happy little bushes here.",
    editing: false,
    saved: false,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "food",
  },
  {
    id: "2019121834505",
    title:
      "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    editing: false,
    saved: true,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "travel",
  },
  {
    id: "2019121834504",
    title:
      "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    editing: false,
    saved: true,
    votes: 0,
    date: 1645774464626,
    user: "n00bMaster69",
    topic: "hobbies",
  },
];
// }
export default data;
